import { Analytics } from "@vercel/analytics/react";
import { Inter, Lato } from "next/font/google";
import Script from "next/script";
import Footer from "./components/Footer";
import Nav from "./components/Nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({
  weight: ["700", "400"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.variable} font-sans`}>
        <Nav />
        {children}
        <Footer />
        <Analytics />
      </body>
      <Script id="worklet">
        {`if (window && CSS.paintWorklet)
        {CSS.paintWorklet?.addModule("bauhaus.js")}`}
      </Script>
    </html>
  );
}
